### ISSUE TITLE
nagiosgraph.js is not installed or wrong version.

### ISSUE THREAD

**Issue by stonio** [JasonRivers/Docker-Nagios#10]
In page http://192.168.99.100:32770/cgi-bin/show.cgi?host=localhost&service=Total%20Processes. Graphs are properly displayed but there are two red alert boxes at the top of the page: "_JavaScript is disabled._" and "_nagiosgraph.js is not installed or wrong version._". However I see that nagiosgraph.js (versio 1.7) is properly loaded.

**Comment by JasonRivers** [comment]
With a default pull of the image, I'm not seeing this at all, are you blocking Javascript in your browser? Please could you try a different browser, I'm currently running Chrome 55.0.2883.44 beta on Ubuntu 16.04.

Jason

**Comment by stonio** [comment]
It's a nagiosgraph  bug caused by malformed *.rdd files containing character `%`.

Reference: https://sourceforge.net/p/nagiosgraph/discussion/394748/thread/085cac2f/ .
