### ISSUE TITLE
Nagios 4.4.5

### ISSUE THREAD

**Issue by hubbertj** [JasonRivers/Docker-Nagios#105]
Current when you open the dashboard it gives a "A new version of Nagios Core is available!" I assume I can turn this off but just wondering if you're going to update your docker image to Nagios 4.4.5.

**Comment by rogerniesten** [comment]
This is already requested in pull request https://github.com/JasonRivers/Docker-Nagios/pull/103
So to my opinion this issue can be closed

**Comment by lukvdborne** [comment]
Still awaiting approval from Jason ;)
