### ISSUE TITLE
Update nagios-plugins to 2.3.1+

### ISSUE THREAD

**Issue by instantlinux** [JasonRivers/Docker-Nagios#111]
It's been 2-1/2 years since the last update but there is finally a much-needed refresh of the plugins available as 2.3.1 from https://github.com/nagios-plugins/nagios-plugins.

**Comment by tronyx** [comment]
I try to keep my fork of this image up to date, and just updated plugins to 2.4.0 on my `:develop` tag which I will be pushing to master later today:

https://github.com/tronyx/Docker-Nagios

**Comment by instantlinux** [comment]
I too have published a separate Nagios image ever since this one fell out of date in 2019. See https://hub.docker.com/r/instantlinux/nagios. At this point there are several of us doing our own images; JasonRivers has been doing a better job keeping up in the past year or so.

This issue is still open despite the problem being fixed for over half a year. Closing it myself.
