### ISSUE TITLE
AH00558: apache2: Could not reliably determine the server's fully qualified domain name

### ISSUE THREAD

**Issue by stonio** [JasonRivers/Docker-Nagios#12]
I have this warning at startup:

> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message

**Comment by bird1235456** [comment]
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 29 12:34:29.145285 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.1 configured -- resuming normal operations
