### ISSUE TITLE
Add ":4.4.6" tag to most recent build in docker

### ISSUE THREAD

**Issue by Kolossi** [JasonRivers/Docker-Nagios#127]
@JasonRivers 

Thanks so much for this docker image, I've been using it for over 2 years. 👍🏻 

The 4.4.6 build is currently only available from docker hub using the "jasonrivers/nagios:latest" tag.

Please tag it as "jasonrivers/nagios:4.4.6"

There's a number of reasons never to consume a docker image using a ":latest" tag - [this medium article](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375) explains it well.

TL;DR - 1) if you'd previously pulled a 4.4.5 image tagged with ":latest", local caching means it might not update when you hope. 2) if as owner you do a rebuild of 4.4.4 because there is an issue, by default that will get the ":latest" tag so consumers may get an older version than they expect etc. etc.

Obviously if you want to continue with ":latest" tag despite the above that's your choice (I get it makes install section of readme not need to be edited each time! 😄 ), but please add "jasonrivers/nagios:4.4.6" too. 🙏🏻

**Comment by JasonRivers** [comment]
I've pushed a :4.4.6 tag - I normally do this at the end of the cycle when I upgrade to the next version, however, I see the reasons behind using a tag in production!

**Comment by Kolossi** [comment]
Great news, thanks @JasonRivers
