### ISSUE TITLE
NSCA Port 5667 Mapping

### ISSUE THREAD

**Issue by wetty** [JasonRivers/Docker-Nagios#131]
Hi,
how do I map to NSCA Port 5667 of the docker nagios to the host?

kind regards
Thomas

**Comment by run2000** [comment]
Publish it at runtime when starting the container

```sh
docker run ... -p 5667:5667
```

**Comment by wetty** [comment]
I did try that, but my Nagios Clients then reported
Error: Could not connect to host xxx on port 5667
The only way so far is to run it in the host network.

**Comment by run2000** [comment]
Hmmm. I can do a basic connectivity test ok here. Not a firewall setting on the host?

**Comment by wetty** [comment]
I dont think so, as I have spent several hours to get a solution, back in September.
As far as I remember another Docker Host on one of my vserver even does not allow me to publish port 5667 as it was not published by the dockerfile

May be extend
EXPOSE 80
To
EXPOSE 80, 5667 might fix it

**Comment by wetty** [comment]
I did try the latest version, with port 5667 exposed.
I publish port 80 and port 5667 and get the following log entries 
nsca[49]: Network server bind failure (99: Cannot assign requested address)

I can access the web UI but the clients can not access nsca on port 5667.

It still works when the container is in the host or macvlan network
