### ISSUE TITLE
ssh connection?

### ISSUE THREAD

**Issue by geryescalier** [JasonRivers/Docker-Nagios#134]
Hello, I am using this container in gns3 and I would like to be able to connect from ssh to make the configurations.
This is possible ?
thank you

**Comment by JasonRivers** [comment]
The container doesn't host an SSH server, it's generally better to mount your configurations in using a volume mount, this way your configurations remain even after an update to the container.

**Comment by geryescalier** [comment]
Thanks for your answer.
I have been able to enter gns3, right mouse button on docker nagios image > Auxiliary console
