### ISSUE TITLE
Unable to get process status

### ISSUE THREAD

**Issue by Diggeris** [JasonRivers/Docker-Nagios#140]
System info: 

Virtualization: kvm
Operating System: Ubuntu 20.04.4 LTS
Kernel: Linux 5.4.0-124-generic
Architecture: x86-64

SeLinux is disabled and I got on main screen 

**Unable to get process status** and nothing is working

**Comment by wetty** [comment]
Same Problem here. Problem startet with Nagios Version 4.4.7
Ubuntu 20.04.4 LTS (GNU/Linux 5.15.39-3-pve x86_64)
Running on a proxmox server

**Comment by wetty** [comment]
Hello 
Output ist looking like this and is endless repeating:
nagios: LOG VERSION: 2.0
wproc: Successfully registered manager as @wproc with query handlernagios: qh: Socket '/opt/nagios/var/rw/nagios.qh' successfully initialized
nagios: qh: core query handler registered
nagios: qh: echo service query handler registered
nagios: qh: help for the query handler registered
nagios: wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 52437;pid=52437nagios: wproc: Registry request: name=Core Worker 52437;pid=52437
wproc: Registry request: name=Core Worker 52436;pid=52436nagios: wproc: Registry request: name=Core Worker 52436;pid=52436
wproc: Registry request: name=Core Worker 52435;pid=52435nagios: wproc: Registry request: name=Core Worker 52435;pid=52435
wproc: Registry request: name=Core Worker 52434;pid=52434nagios: wproc: Registry request: name=Core Worker 52434;pid=52434
wproc: Registry request: name=Core Worker 52433;pid=52433nagios: wproc: Registry request: name=Core Worker 52433;pid=52433
wproc: Registry request: name=Core Worker 52432;pid=52432nagios: wproc: Registry request: name=Core Worker 52432;pid=52432
checking permissions for nagios & nagiosgraph
nagios: Nagios 4.4.7 starting... (PID=52438)
nagios: Local time is Fri Aug 26 11:36:32 CEST 2022
nagios: LOG VERSION: 2.0
Nagios Core 4.4.7
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2022-04-14

License: GPL
Website: https://www.nagios.org
Nagios 4.4.7 starting... (PID=52438)
Local time is Fri Aug 26 11:36:32 CEST 2022
nagios: qh: Socket '/opt/nagios/var/rw/nagios.qh' successfully initialized
nagios: qh: core query handler registered
nagios: qh: echo service query handler registered
nagios: qh: help for the query handler registered
nagios: wproc: Successfully registered manager as @wproc with query handler
wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 52445;pid=52445nagios: wproc: Registry request: name=Core Worker 52445;pid=52445
wproc: Registry request: name=Core Worker 52444;pid=52444nagios: wproc: Registry request: name=Core Worker 52444;pid=52444
wproc: Registry request: name=Core Worker 52443;pid=52443nagios: wproc: Registry request: name=Core Worker 52443;pid=52443
wproc: Registry request: name=Core Worker 52442;pid=52442nagios: wproc: Registry request: name=Core Worker 52442;pid=52442
wproc: Registry request: name=Core Worker 52441;pid=52441nagios: wproc: Registry request: name=Core Worker 52441;pid=52441

**Comment by Diggeris** [comment]
and it's looping.

checking permissions for nagios & nagiosgraph
nagios: Nagios 4.4.7 starting... (PID=1421)
nagios: Local time is Fri Aug 26 23:02:06 UTC 2022
nagios: LOG VERSION: 2.0

Nagios Core 4.4.7
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2022-04-14
License: GPL

Website: https://www.nagios.org
Nagios 4.4.7 starting... (PID=1421)
Local time is Fri Aug 26 23:02:06 UTC 2022
nagios: qh: Socket '/opt/nagios/var/rw/nagios.qh' successfully initialized
nagios: qh: core query handler registered
nagios: qh: echo service query handler registered
nagios: qh: help for the query handler registered
nagios: wproc: Successfully registered manager as @wproc with query handler
wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 1425;pid=1425nagios: wproc: Registry request: name=Core Worker 1425;pid=1425

wproc: Registry request: name=Core Worker 1426;pid=1426nagios: wproc: Registry request: name=Core Worker 1426;pid=1426

wproc: Registry request: name=Core Worker 1424;pid=1424nagios: wproc: Registry request: name=Core Worker 1424;pid=1424

wproc: Registry request: name=Core Worker 1423;pid=1423nagios: wproc: Registry request: name=Core Worker 1423;pid=1423

checking permissions for nagios & nagiosgraph
nagios: Nagios 4.4.7 starting... (PID=1427)
nagios: Local time is Fri Aug 26 23:02:08 UTC 2022
nagios: LOG VERSION: 2.0

**Comment by derfredy** [comment]
Mine is also looping. Any clue?

**Comment by derfredy** [comment]
Mine is also looping...
Did you find any reason mates?
@JasonRivers
