### ISSUE TITLE
Nagios with HTTPS

### ISSUE THREAD

**Issue by stonio** [JasonRivers/Docker-Nagios#23]
* How can I use Nagios via HTTPS ?
* How can I mount my SSL certificates?

**Comment by JasonRivers** [comment]
The container doesn't do anything with HTTPS (and I don't intend to implement it within the image), the best way to use HTTPS is to use a reverse proxy using nginx, haproxy, etc.

See the following:
https://github.com/GoogleCloudPlatform/nginx-ssl-proxy
https://github.com/tutumcloud/haproxy
https://hub.docker.com/r/yajo/https-proxy/

I'm using the HAProxy as part of Rancher to supply https to the container.
