### ISSUE TITLE
how to reload nagios ?

### ISSUE THREAD

**Issue by cxadmin** [JasonRivers/Docker-Nagios#32]
As I understand the only way to apply changes is to restart docker container?
IS there any other options to reload nagios?

**Comment by JasonRivers** [comment]
There is a way to do this from within the web panel for nagios.
On the left hand menu select "Process Info" (near the bottom under System) and then select "Restart the Nagios process"

This will trigger nagios to stop and start reloading any new configuration, - be aware that if there are errors in your configuration then the nagios process will fail to restart, it's a good idea to check that the config is OK using:

```
nagios -v /opt/nagios/etc/nagios.cfg
```

**Comment by cxadmin** [comment]
Thank you.
Exectly what I need.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by coolminds-tech** [comment]
When I tried to restart I got following error

Error: Could not open command file '/opt/nagios/var/rw/nagios.cmd' for update!
The permissions on the external command file and/or directory may be incorrect. Read the FAQs on how to setup proper permissions.
An error occurred while attempting to commit your command for processing.

**Comment by blue212121** [comment]
if you want to use the cli to reload nagios (to pick up config changes) instead of restarting the full container or using the webgui, you can send the SIGHUP signal to the process after checking the config validity

this is how i do it:

```
# to check config validity
docker exec -it nagios /opt/nagios/bin/nagios -v /opt/nagios/etc/nagios.cfg

# to reload config
docker exec -it nagios /usr/bin/sv hup nagios
```

https://smarden.org/runit/sv.8
