### ISSUE TITLE
libnagios-plugin-perl

### ISSUE THREAD

**Issue by krisavi** [JasonRivers/Docker-Nagios#33]
Would it be possible to include libnagios-plugin-perl in the apt installation list as well? 

I have one perl plugin and it requires it to be installed, tried to override run command to apt install it and then run nagios, but seems not to work like that.

edit: found a solution, running bash -c "apt install -y libnagios-plugin-perl && /usr/local/bin/start_nagios"

**Comment by JasonRivers** [comment]
Once it's built by Dockerhub, the latest version should have this. I think I had intended to include this as I had already included libnagios-object-perl
