### ISSUE TITLE
Define as volumes the etc and var dir of the nagiosgraph installation

### ISSUE THREAD

**Issue by jtome** [JasonRivers/Docker-Nagios#41]
First of all, congratulations and thanks for this project.

Second, I would like to suggest to define as docker volumes also the directories of Nagiosgraph....

- /opt/nagiosgraph/etc
- /opt/nagiosgraph/var

At least in my case I usually have to made some adjusts in the Nagiosgraph configuration in order to support the different services I define in Nagios (in the datasetdb.conf file) and also I think that it is important to be able to persist the graphs generated by Nagiosgraph (that are located in the var directory).

Thanks in advance.

**Comment by JasonRivers** [comment]
Commit d4d3ea3 should have the changes for this, so the next build should be good to go.
As a side note - you can mount any directory within the container even if it's not explicitly mentioned in the volumes.

**Comment by jtome** [comment]
Thanks a lot @JasonRivers. I will make some tests in order to verify this is working ok
