### ISSUE TITLE
How to add config .cfg files to the image

### ISSUE THREAD

**Issue by crisp2u** [JasonRivers/Docker-Nagios#43]
Hi,

I'm trying to extend your image and I'm trying to add my .cfg files into etc/conf.d dir. 
I must be doing something wrong because after starting the container the folder is empty.

I tried also putting them in /orig/etc/conf.d with no luck.

Thanks

**Comment by JasonRivers** [comment]
The best way to do this is to mount /opt/nagios/etc as an external volume and put your configuration in there. The config in /opt/nagios/etc is only meant as an example and is included as part of building Nagios

**Comment by crisp2u** [comment]
I understand and that worked out of the box, but I wanted a way to build an image with configuration files inside. 
Actually this is working now by adding them to the /orig folder, I was probably doing some else at the same time. You can close this, thanks!
