### ISSUE TITLE
Cannot customize Postfix configuration

### ISSUE THREAD

**Issue by stonio** [JasonRivers/Docker-Nagios#45]
Can you allow Postfix configuration? 

Maybe expose file `/etc/postfix/main.cf`.

I need settings:
- relayhost
- inet_protocols

**Comment by JasonRivers** [comment]
It was already possible to override the relay host, but I've added inet_protocols, too
you can set these using environment variables when launching the container:

MAIL_RELAY_HOST
MAIL_INET_PROTOCOLS

The relay host defaults to nothing, and the inet_protocols defaults to "all" options are: all, ipv4, ipv6
