### ISSUE TITLE
Bulk Questions

### ISSUE THREAD

**Issue by ameyaagashe** [JasonRivers/Docker-Nagios#54]
Hi Jason,

I have few questions and would appreciate your assistance. I could launch Nagios UI and see localhost in it.

I would like to know how to monitor its own host and another host. Do you have documentation for that ?

Please advise

Thanks
Ameya

**Comment by JasonRivers** [comment]
Hi @ameyaagashe 

The best thing to do is to read the nagios core documentation here: https://www.nagios.org/documentation/

Once you have your configuration you should mount it in to /opt/nagios/etc for nagios to pick it up and use it, to monitor services on a remote host you can use either NRPE or NCPA.
for NRPE documentation see here: https://assets.nagios.com/downloads/nagioscore/docs/nrpe/NRPE.pdf
for NCPA documentation see here: https://www.nagios.org/ncpa/help.php

Jason
