### ISSUE TITLE
SMTP relay host gets overwritten when I start nagios?

### ISSUE THREAD

**Issue by SigmaOutdoors** [JasonRivers/Docker-Nagios#60]
Hopefully someone can help me with this, I am trying to set my relay host on container start up (/etc/postfix/main.cf), and if I look in my log file, it does get set, however after nagios starts I go look in the main.cf file and it is back to unset  "relayhost ="

sed -i "s/relayhost =/relayhost =${SMTP_HOST}/g" /etc/postfix/main.cf
cat /etc/postfix/main.cf | grep relayhost >>  /tmp/container-startup.log
# We set the relay host in main.cf and then once we start nagios it gets blown away
echo "STARTUP Starting nagios..."
/usr/local/bin/start_nagios

Does anyone know why this is?  As a bonus question, somehow between my host and container, it is picking up my real corporate SMTP host to send mail through and I have no idea how it is doing that, I never told the image to use my corporate SMTP server.

**Comment by JasonRivers** [comment]
How are you setting the SMTP Relay?

**Comment by SigmaOutdoors** [comment]
I made my own Dockerfile to  install a few other packages and a script as my ENTRYPOINT, the script does a sed to replace the relayhost and then starts nagios.

**Dockerfile**
```
FROM jasonrivers/nagios:latest
COPY ./dep/container-startup.sh /usr/bin/
RUN  apt-get update; \
    apt-get install vim -y; \
    apt-get install telnet -y; \
    chmod 777 /usr/bin/container-startup.sh;

# Set the entry point for the docker image.
ENTRYPOINT ["/usr/bin/container-startup.sh"]
```

**container-startup.sh**
```
#!/bin/sh
# need to /etc/postfix/main.cf to add our SMTP server as relay host
echo "STARTUP Adjusting SMTP_HOST..."
#Send to the log what we passed in the env
echo "SMTP_HOST=${SMTP_HOST}" >> /tmp/container-startup.log
#replace relayhost with our host
sed -i "s/relayhost =/relayhost =${SMTP_HOST}/g" /etc/postfix/main.cf
#echo to Docker log and write to our log to prove we have done the replace
cat /etc/postfix/main.cf | grep relayhost
cat /etc/postfix/main.cf | grep relayhost >>  /tmp/container-startup.log
# We set the relay host in main.cf and then once we start nagios it gets blown away, and reset to empty
echo "STARTUP Starting nagios..."
/usr/local/bin/start_nagios
```
**Results from within Containter**
My log shows that I changed it, but when I go and look it is back to relayhost=
```
# cat  /tmp/container-startup.log
SMTP_HOST=12.14.25.151
relayhost =12.14.25.151
#
# cat /etc/postfix/main.cf | grep relayhost
relayhost =
#
```
And that bonus question I talked about...how is this picking up my corporate email server?   I know WHY it is bouncing and I can fix that by just giving a valid corporate email from address. What I don't get is where the nagios container is getting THAT IP & and SMTP host from...I didn't set it anywhere.  The servers and IPs in the log below have been obfuscated.
**Docker Log**

`postfix/smtp[8964]: 21F2C1805507: to=<me@mycompany.com>, relay=mycompany-mx01.com[12.22.8.37]:25, delay=0.29, delays=0.15/0/0.07/0.06, dsn=7.1.2, status=bounced (host mycompany-mx01.com[12.22.8.37] said: 504 7.1.2 <nagios@a123acfdf44d>: Sender address rejected: need fully-qualified address (in reply to RCPT TO command))
`

**Comment by thinkitdata** [comment]
Alternatively you can have a simple script that executes:
postconf -e "relayhost=YOURSMTPRELAY"
postfix reload

whenever your container is started....

**Comment by JasonRivers** [comment]
The problem here is that you're still calling /usr/local/bin/start_nagios which I assume you have not modified, this script then starts runsvdir on /erc/service - which I again assume you did not change any of the contents of.
In the postfix/run script there is this line:
sed -i "s/relayhost =.*/relayhost = ${MAIL_RELAY_HOST}/" /etc/postfix/main.cf
which is what is replacing it before postfix has started. This could be better by checking MAIL_RELAY_HOST first, and also using postconf, but you'll need to edit this script too. Alternatively, just use: ```-e MAIL_RELAY_HOST=mail.example.com``` when you start the container.
