### ISSUE TITLE
Nagios does not verify config correctly with bind mounts

### ISSUE THREAD

**Issue by braamvh** [JasonRivers/Docker-Nagios#68]
Greetings,

I can run Nagios given the config in the image, but I run into issues when I create my own config.  I am not sure if I am making a mistake running Nagios in the way I do, though.

Since I only removed the **localhost.cfg** and added 3 more simple hosts, I can't see where my error is.

# **Steps I have taken**:
Get image:
---------
- docker pull jasonrivers/nagios:4.3.2

Get data from inside container:
------------------------------
- docker run --name nagios4 -p 0.0.0.0:8080:80 jasonrivers/nagios:4.3.2
- docker exec -it nagios4 bash
- <create tar archive of /opt>
- docker cp nagios4:/opt.tar .
- docker stop nagios4
- docker rm nagios4

Customize:
---------
- Copy contents of /opt/nagios/etc and structure for /opt/nagios/var into bind mounts (no files), repeat for /opt/nagiosgraph
- Add new hosts and commands

Run Nagios with bind mounts:
---------------------------
- docker run -p 8080:80 --mount type=bind,source=/srv/conf/nagios,target=/opt/nagios/etc --mount type=bind,source=/srv/db/nagios,target=/opt/nagios/var --mount type=bind,source=/srv/conf/nagiosgraph,target=/opt/nagiosgraph/etc --mount type=bind,source=/srv/db/nagiosgraph,target=/opt/nagiosgraph/var/rrd --mount type=bind,source=/srv/logs/nagiosgraph,target=/opt/nagiosgraph/var/log --name=sce-1-nagios -d jasonrivers/nagios:4.3.2

- Top of my nagios.cfg (removing #):
```
log_file=/opt/nagios/var/nagios.log
cfg_file=/opt/nagios/etc/objects/commands.cfg
cfg_file=/opt/nagios/etc/objects/contacts.cfg
cfg_file=/opt/nagios/etc/objects/timeperiods.cfg
cfg_file=/opt/nagios/etc/objects/templates.cfg
cfg_dir=/opt/nagios/etc/conf.d/
object_cache_file=/opt/nagios/var/objects.cache
precached_object_file=/opt/nagios/var/objects.precache
resource_file=/opt/nagios/etc/resource.cfg
status_file=/opt/nagios/var/status.dat
```

- Host 1 definition (Removing #):
```
define host{
        use                     linux-server         
        host_name               sce-1.concurrent.systems
        alias                   sce-1.concurrent.systems
        address                	<removed> 
        }
define service{
        use                             local-service,graphed-service  
        host_name                       sce-1.concurrent.systems
        service_description             PING
	check_command			check_ping!100.0,20%!500.0,60%
        }
```

- There are 2 more hosts defined identically, just with different names.

- Docker logs sce-1-nagios:
```
Nagios Core 4.3.2
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2017-05-09
License: GPL

Website: https://www.nagios.org
Nagios 4.3.2 starting... (PID=4820)
Local time is Tue May 29 13:26:52 UTC 2018
nerd: Channel hostchecks registered successfully
nerd: Channel servicechecks registered successfully
nerd: Channel opathchecks registered successfully
nerd: Fully initialized and ready to rock!
wproc: Successfully registered manager as @wproc with query handler
nagios: Nagios 4.3.2 starting... (PID=4820)
nagios: Local time is Tue May 29 13:26:52 UTC 2018
nagios: LOG VERSION: 2.0
nagios: qh: Socket '/opt/nagios/var/rw/nagios.qh' successfully initialized
nagios: qh: core query handler registered
nagios: nerd: Channel hostchecks registered successfully
nagios: nerd: Channel servicechecks registered successfully
nagios: nerd: Channel opathchecks registered successfully
nagios: nerd: Fully initialized and ready to rock!
nagios: wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 4821;pid=4821
nagios: wproc: Registry request: name=Core Worker 4821;pid=4821
wproc: Registry request: name=Core Worker 4822;pid=4822
nagios: wproc: Registry request: name=Core Worker 4822;pid=4822
wproc: Registry request: name=Core Worker 4823;pid=4823
nagios: wproc: Registry request: name=Core Worker 4823;pid=4823
wproc: Registry request: name=Core Worker 4824;pid=4824
Warning: Duplicate definition found for host 'sce-1.concurrent.systems' (config file '/opt/nagios/etc/conf.d/sce-1.cfg', starting on line 24)
Error: Could not add object property in file '/opt/nagios/etc/conf.d/sce-1.cfg' on line 28.
Error: Invalid max_check_attempts value for host 'sce-1.concurrent.systems'
Error: Could not register host (config file '/opt/nagios/etc/conf.d/sce-1.cfg', starting on line 24)
Bailing out due to one or more errors encountered in the configuration files. Run Nagios from the command line with the -v option to verify your config before restarting. (PID=4820)
nagios: wproc: Registry request: name=Core Worker 4824;pid=4824
nagios: Warning: Duplicate definition found for host 'sce-1.concurrent.systems' (config file '/opt/nagios/etc/conf.d/sce-1.cfg', starting on line 24)
nagios: Error: Could not add object property in file '/opt/nagios/etc/conf.d/sce-1.cfg' on line 28.
nagios: Error: Invalid max_check_attempts value for host 'sce-1.concurrent.systems'
nagios: Error: Could not register host (config file '/opt/nagios/etc/conf.d/sce-1.cfg', starting on line 24)
nagios: Bailing out due to one or more errors encountered in the configuration files. Run Nagios from the command line with the -v option to verify your config before restarting. (PID=4820)
nagios: Event broker module 'NERD' deinitialized successfully.
```

Running `nagios -v` inside the container give the same errors as above.

**Comment by braamvh** [comment]
OK, I managed to get this to run, but this leaves me more confused.  I copied the files out of `conf.d` and into `objects`, and specifically mentioned them in `cfg-file` directives.

And no more verification errors, with Nagios starting up correctly.  I am not 100% sure why cfg_dir is not working, but that would make large-scale deployments faster.

**Comment by JasonRivers** [comment]
I will take a look at this and add more checking for the configs before starting Nagios.
In the meantime, you can run the following command:
```
docker exec -it sce-1-nagios /opt/nagios/bin/nagios -v /opt/nagios/etc/nagios.cfg
```
which may give you more clues as to what is wrong with the config.

**Comment by braamvh** [comment]
Since I have it running (albeitly for cfg_file and not cfg_dir) I am going to leave it as is for now.

Thanks
