### ISSUE TITLE
raspberry pi 3 crash

### ISSUE THREAD

**Issue by antoniosap** [JasonRivers/Docker-Nagios#69]
```
WARNING: Published ports are discarded when using host network mode
standard_init_linux.go:190: exec user process caused "exec format error"
```

**Comment by JasonRivers** [comment]
I'm not sure I understand this issue report, Are you running the container on the Raspberry Pi?

**Comment by antoniosap** [comment]
yes. have docker-ce 18 on rpi pi 3

docker pull jasonrivers/nagios:latest  <--- OK

and 

docker run --name nagios4 -p 0.0.0.0:8080:80 jasonrivers/nagios:latest

give me this error

**Comment by JasonRivers** [comment]
Sorry, This image is only supported on amd64 architecture, I have no intention on supporting ARM with this as Nagios can be rather heavy when monitoring many hosts/services
