### ISSUE TITLE
check_disk plugin shows localhost storage rather than Remote Storage

### ISSUE THREAD

**Issue by quickbooks2018** [JasonRivers/Docker-Nagios#78]
Dear,
Hope you are well, check_disk plugin shows the existing host storage rather than remote server, any solution to fix the problem? It seems that this docker nagios is not a solution for adding remote hosts?

Regards

**Comment by JasonRivers** [comment]
check_disk is a local check for Nagios - you should look in to NCPA or NRPE for remote checks.
