### ISSUE TITLE
A little question about nagios.cfg

### ISSUE THREAD

**Issue by ethnchao** [JasonRivers/Docker-Nagios#8]
In Dockerfile, line 154~157, you've already change the nagios.cfg, :

`echo "use_timezone=$NAGIOS_TIMEZONE" >> ${NAGIOS_HOME}/etc/nagios.cfg			&&	\
	echo "SetEnv TZ \"${NAGIOS_TIMEZONE}\"" >> /etc/apache2/conf-enabled/nagios.conf	&&	\
	echo "cfg_dir=${NAGIOS_HOME}/etc/conf.d" >> ${NAGIOS_HOME}/etc/nagios.cfg		&&	\
	echo "cfg_dir=${NAGIOS_HOME}/etc/monitor" >> ${NAGIOS_HOME}/etc/nagios.cfg		&&	\`

Why ADD nagios.cfg again in line 167 ?
`ADD nagios/nagios.cfg /opt/nagios/etc/nagios.cfg`

It looks like will be override, I think.

**Comment by JasonRivers** [comment]
This was because I changed the way I was dealing with the nagios.cfg at commit 1a0848dd but I failed to remove the old parts.

Thanks for noticing this I'll sort it out to save confusion!
